In [10]:
#sigh=alpha(0)+beta(1)
import numpy as np
a=np.array([1,0])
b=np.array([0,1])
print(a,b)
c=(a+b)/np.sqrt(2)
print(c)
d=(a-b)/np.sqrt(2)
print(d)

#alpha=float(input("enter the value of alpha= "))
#beta=float(input("enter the value of beta= "))
#print(alpha,beta)


[1 0] [0 1]
[ 0.70710678  0.70710678]
[ 0.70710678 -0.70710678]


In [18]:
a=np.array([[1,1j]])
A=a/np.sqrt(2)
C=A.conj().T
#print(A)
print(C)

[[ 0.70710678-0.j        ]
 [ 0.00000000-0.70710678j]]


In [28]:
z=np.array([[1,0],[0,-1]])
print(z)
print(z[1,1])


[[ 1  0]
 [ 0 -1]]
-1


In [37]:
psi=np.array([0,1])
z=np.array([[1,0],[0,-1]])
h=np.array([[1,1],[1,-1]])/np.sqrt(2)
print(psi)
print(z)
print(h)
o=psi @ z @ h
print(o)




[0 1]
[[ 1  0]
 [ 0 -1]]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[-0.70710678  0.70710678]


In [40]:
alpha=float(input("enter the value of alpha= "))
beta=float(input("enter the value of beta= "))
print(str(alpha)+"|0> +" ,str(beta)+"|1>")

enter the value of alpha= .2
enter the value of beta= .8
0.2|0> + 0.8|1>
